#!/usr/bin/env bats
# Tests that the generated-file short-circuits in hooks/run-review.sh run
# BEFORE the diff-size dispatch.
#
# Why this exists: the markdown-only and lockfile-only skips used to sit ~90
# lines downstream of the size dispatch, so a generated-file commit large
# enough to trip `review.skipThreshold` was hard-blocked and could never reach
# the exemption written for it. A regenerated lockfile is one indivisible
# file, so the error's "split into smaller commits" advice is unavailable, and
# its other suggestion (raise `review.skipThreshold`) only reroutes the commit
# into a chunked review that fails on the oversized chunk. Issue #427.
#
# The assertions below are ordering tripwires: each stages a generated-file
# diff LARGER than both thresholds and requires a clean skip. Under the old
# ordering every one of them blocks instead.
#
# Run: bats ~/.claude/tests/test_run_review_generated_file_skip_order.bats

# Resolve the script under test relative to THIS test file, not via
# ${HOME}/.claude/hooks — that path is a symlink to the main working
# directory, so in a git worktree it would silently exercise main's copy
# instead of the branch under test.
SCRIPT="${BATS_TEST_DIRNAME}/../hooks/run-review.sh"

setup() {
  TMPDIR_TEST="$(mktemp -d)"
  export TMPDIR_TEST
  git -C "${TMPDIR_TEST}" init -q
  git -C "${TMPDIR_TEST}" checkout -q -b test-branch
  git -C "${TMPDIR_TEST}" config user.email "test@test.com"
  git -C "${TMPDIR_TEST}" config user.name "Test"
  touch "${TMPDIR_TEST}/init.txt"
  git -C "${TMPDIR_TEST}" add init.txt
  GIT_CONFIG_GLOBAL=/dev/null git -C "${TMPDIR_TEST}" commit -q -m "initial commit message"

  export EXPECTED_LOG="${TMPDIR_TEST}/.git/last-review-result.log"

  # Mock claude CLI. The --version preflight must NOT consume stdin, or it
  # drains the diff that run-review.sh later reads via DIFF=$(cat).
  #
  # The agent branch emits FAIL deliberately: these tests assert the script
  # never reaches the reviewer at all. If a skip regresses and the reviewer
  # does get invoked, the FAIL makes that visible instead of letting an
  # accidental PASS mask the ordering bug.
  MOCK_DIR="$(mktemp -d)"
  export MOCK_DIR
  export AGENT_INVOKED="${MOCK_DIR}/agent-invoked"
  cat >"${MOCK_DIR}/claude" <<EOF
#!/usr/bin/env bash
for a in "\$@"; do
  if [[ "\$a" == "--version" ]]; then
    echo "mock-claude 0.0.1"
    exit 0
  fi
done
touch "${AGENT_INVOKED}"
cat > /dev/null
# --output-format json envelope (claude-config#443). blocking:true so that a
# regressed skip is caught by the gate, not merely by the prose.
jq -n '{type:"result",subtype:"success",is_error:false,
        result:"VERDICT: FAIL\nSEVERITY: BLOCKING\nreviewer should not have been reached",
        structured_output:{verdict:"FAIL",blocking:true,findings:[]}}'
EOF
  chmod +x "${MOCK_DIR}/claude"
  export CLAUDE_CLI="${MOCK_DIR}/claude"
}

teardown() {
  rm -rf "${TMPDIR_TEST}" "${MOCK_DIR}"
}

# Write a file with enough lines that the staged diff exceeds the default
# skipThreshold (2500) — the hard-block branch, the one with no viable
# remedy for a generated file.
_write_big_file() {
  local path="$1" lines="${2:-4000}"
  local i
  : >"${TMPDIR_TEST}/${path}"
  for ((i = 0; i < lines; i += 1)); do
    printf 'generated line %d\n' "${i}" >>"${TMPDIR_TEST}/${path}"
  done
}

# The `cd` here is not a git invocation, so the repo's `git -C` convention does
# not apply: run-review.sh reads the staged index of its OWN working directory,
# so it must be launched from inside the temp repo. It runs in a subshell so
# the directory change cannot leak into the parent bats process, and uses
# `return 1` rather than `exit 1` so one broken test does not tear down the
# whole suite. Same pattern as tests/test_run_review_message_file.bats.
# GIT_CONFIG_GLOBAL=/dev/null keeps the developer's own `review.*` keys (for
# example a raised skipThreshold) from leaking in and changing the routing.
_run_review() {
  local diff
  diff=$(git -C "${TMPDIR_TEST}" diff --cached)
  (
    cd "${TMPDIR_TEST}" || return 1
    printf '%s\n' "${diff}" \
      | REVIEW_LOG="${EXPECTED_LOG}" CLAUDE_CLI="${CLAUDE_CLI}" \
        GIT_CONFIG_GLOBAL=/dev/null bash "${SCRIPT}" "$@"
  )
}

@test "large lockfile-only diff skips review instead of hard-blocking on size" {
  _write_big_file "package-lock.json"
  git -C "${TMPDIR_TEST}" add package-lock.json

  run _run_review
  [ "$status" -eq 0 ]
  [[ "$output" == *"Lockfile-only changes detected"* ]]
  grep -q 'skipped: lockfile-only' "${EXPECTED_LOG}"
}

@test "large terraform-lockfile-only diff skips review instead of hard-blocking on size" {
  # `.terraform.lock.hcl` is generated by `terraform providers lock` and is as
  # unreviewable as any other lockfile, but it was absent from the exemption
  # pattern, so a fleet-wide relock (564 files / ~42k lines in
  # beacon-biosignals/infra) hard-blocked on size with no viable remedy.
  # Nested path, because these are never at the repo root.
  mkdir -p "${TMPDIR_TEST}/terraform/repositories/example"
  _write_big_file "terraform/repositories/example/.terraform.lock.hcl"
  git -C "${TMPDIR_TEST}" add terraform/repositories/example/.terraform.lock.hcl

  run _run_review
  [ "$status" -eq 0 ]
  [[ "$output" == *"Lockfile-only changes detected"* ]]
  grep -q 'skipped: lockfile-only' "${EXPECTED_LOG}"
}

@test "a large diff mixing code with terraform lockfiles is still reviewed" {
  # Same all-or-nothing guard as the package-lock case: adding the Terraform
  # pattern must not let a .tf change ride along unreviewed.
  mkdir -p "${TMPDIR_TEST}/terraform/repositories/example"
  _write_big_file "terraform/repositories/example/.terraform.lock.hcl"
  echo 'resource "aws_iam_policy" "x" {}' >"${TMPDIR_TEST}/main.tf"
  git -C "${TMPDIR_TEST}" add terraform/repositories/example/.terraform.lock.hcl main.tf

  run _run_review
  [ "$status" -ne 0 ]
  [[ "$output" != *"Lockfile-only changes detected"* ]]
  grep -q 'blocked: diff too large' "${EXPECTED_LOG}"
}

@test "large markdown-only diff skips review instead of hard-blocking on size" {
  _write_big_file "README.md"
  git -C "${TMPDIR_TEST}" add README.md

  run _run_review
  [ "$status" -eq 0 ]
  [[ "$output" == *"Markdown-only changes detected"* ]]
  grep -q 'skipped: markdown-only' "${EXPECTED_LOG}"
}

@test "large generated-file diff never reaches the reviewer agent" {
  _write_big_file "package-lock.json"
  git -C "${TMPDIR_TEST}" add package-lock.json

  run _run_review
  [ "$status" -eq 0 ]
  [ ! -f "${AGENT_INVOKED}" ]
}

@test "diff between maxLines and skipThreshold skips rather than chunking" {
  # Sized into the chunked-review band: above review.maxLines (1000) but
  # below review.skipThreshold (2500). This is the band the issue's
  # workaround #2 lands in, where chunked review reports zero findings and
  # blocks anyway on the oversized chunk.
  _write_big_file "yarn.lock" 1500
  git -C "${TMPDIR_TEST}" add yarn.lock

  run _run_review
  [ "$status" -eq 0 ]
  [[ "$output" == *"Lockfile-only changes detected"* ]]
  [[ "$output" != *"chunked"* ]]
}

@test "a large diff mixing code with generated files is still reviewed" {
  # The skips must remain ALL-or-nothing. Moving them earlier must not let a
  # code change ride along inside a large generated-file commit unreviewed:
  # here the size dispatch is still the correct handler.
  _write_big_file "package-lock.json"
  echo "def exploit(): pass" >"${TMPDIR_TEST}/app.py"
  git -C "${TMPDIR_TEST}" add package-lock.json app.py

  run _run_review
  [ "$status" -ne 0 ]
  [[ "$output" != *"Lockfile-only changes detected"* ]]
  grep -q 'blocked: diff too large' "${EXPECTED_LOG}"
}

# --- Artifact-only skip (claude-config#481) ---------------------------------
#
# Data artifacts (scan logs, TSV/CSV exports) are not code. Before #481 a
# commit of 42 scan logs hit the size gate, got split six ways, and each piece
# was AI-reviewed as if it were code. These cases pin the exemption, its
# all-or-nothing guard, and both per-repo overrides Andrew asked for.

@test "artifact-only diff (log + tsv) skips review and says so in the log" {
  mkdir -p "${TMPDIR_TEST}/docs/scan"
  _write_big_file "docs/scan/shellcheck.log"
  _write_big_file "summary.tsv" 200
  git -C "${TMPDIR_TEST}" add docs/scan/shellcheck.log summary.tsv

  run _run_review
  [ "$status" -eq 0 ]
  [[ "$output" == *"Artifact-only changes detected"* ]]
  grep -q 'skipped: artifact-only' "${EXPECTED_LOG}"
  [ ! -f "${AGENT_INVOKED}" ]
}

@test "files under a docs scan/ directory count as artifacts whatever their extension" {
  mkdir -p "${TMPDIR_TEST}/docs/2026-09/scan"
  echo "raw scanner output" >"${TMPDIR_TEST}/docs/2026-09/scan/semgrep.json"
  git -C "${TMPDIR_TEST}" add docs/2026-09/scan/semgrep.json

  run _run_review
  [ "$status" -eq 0 ]
  grep -q 'skipped: artifact-only' "${EXPECTED_LOG}"
}

@test "artifacts mixed with one shell script are still reviewed" {
  _write_big_file "run.log" 200
  printf '#!/usr/bin/env bash\nrm -rf "$1"\n' >"${TMPDIR_TEST}/cleanup.sh"
  git -C "${TMPDIR_TEST}" add run.log cleanup.sh

  run _run_review
  [ "$status" -ne 0 ]
  [[ "$output" != *"Artifact-only changes detected"* ]]
  ! grep -q 'skipped: artifact-only' "${EXPECTED_LOG}"
  [ -f "${AGENT_INVOKED}" ]
}

@test "review.artifactSkip=false in the repo turns the skip off" {
  _write_big_file "data.csv" 200
  git -C "${TMPDIR_TEST}" add data.csv
  git -C "${TMPDIR_TEST}" config review.artifactSkip false

  run _run_review
  [ "$status" -ne 0 ]
  ! grep -q 'skipped: artifact-only' "${EXPECTED_LOG}"
  [ -f "${AGENT_INVOKED}" ]
}

@test "review.artifactPatterns replaces the default list (drop csv, keep log)" {
  git -C "${TMPDIR_TEST}" config review.artifactPatterns '*.log'

  _write_big_file "data.csv" 200
  git -C "${TMPDIR_TEST}" add data.csv
  run _run_review
  [ "$status" -ne 0 ]
  ! grep -q 'skipped: artifact-only' "${EXPECTED_LOG}"

  git -C "${TMPDIR_TEST}" rm -q --cached data.csv
  rm -f "${AGENT_INVOKED}"
  _write_big_file "build.log" 200
  git -C "${TMPDIR_TEST}" add build.log
  run _run_review
  [ "$status" -eq 0 ]
  grep -q 'skipped: artifact-only' "${EXPECTED_LOG}"
  [ ! -f "${AGENT_INVOKED}" ]
}
